# monitoring/prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'orchestrator'
    static_configs:
      - targets: ['orchestrator:9090']

  - job_name: 'speech_recognition'
    static_configs:
      - targets: ['speech_recognition:9090']

  - job_name: 'text_generation'
    static_configs:
      - targets: ['text_generation:9090']

  - job_name: 'tts'
    static_configs:
      - targets: ['tts:9090']
