# docker-compose.yml
version: '3.8'

services:
  orchestrator:
    build: ./services/orchestrator
    ports:
      - "8000:8000"
      - "9091:9090"
    environment:
      - SERVICE_ID=orchestrator_1
    volumes:
      - ./logs:/app/logs

  speech_recognition:
    build: ./services/speech_recognition
    ports:
      - "8001:8000"
      - "9092:9090"
    environment:
      - SERVICE_ID=speech_recognition_1
    volumes:
      - ./logs:/app/logs

  text_generation:
    build: ./services/text_generation
    ports:
      - "8002:8000"
      - "9093:9090"
    environment:
      - SERVICE_ID=text_generation_1
    volumes:
      - ./logs:/app/logs

  tts:
    build: ./services/tts
    ports:
      - "8003:8000"
      - "9094:9090"
    environment:
      - SERVICE_ID=tts_1
    volumes:
      - ./logs:/app/logs

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - prometheus
